<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\CleanProject.Application.csproj" />
    <ProjectReference Include="..\CleanProject.Domain\CleanProject.Domain.csproj" />
    <ProjectReference Include="..\CleanProject.Infra.Data\CleanProject.Infra.Data.csproj" />
    <ProjectReference Include="..\CleanProject.Infra.Ioc\CleanProject.Infra.Ioc.csproj" />
  </ItemGroup>

</Project>
